services:

  payment-redis:
    image: redis:8
    container_name: payment-redis
    restart: unless-stopped
    ports:
      - "6380:6380"
    volumes:
      - payment-redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - payment-network
      
  payment-postgres:
    image: postgres:17-alpine
    container_name: payment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5454:5432"
    volumes:
      - payment-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment-network


volumes:
  payment-postgres-data:
  payment-pgadmin-data:
  payment-rabbitmq-data:
  payment-redis-data:

networks:
  payment-network:
    driver: bridge

      
      

